// src/app/components/banner/banner.component.ts
import { AfterViewInit, Component, ViewChild } from '@angular/core';

@Component({
  selector: 'banner',
  templateUrl: './banner.component.html',
  styleUrls: ['./banner.component.scss']
})

export class BannerComponent implements AfterViewInit {

  title = 'Igor Nascimento';
  splitedTitle = this.title.split('');

  fonts = [
    'butterfly',
    'caesarDressing',
    'cairoVariable',
    'chelseaMarket',
    'comingSoon',
    'constantine',
    'craftyGirls',
    'dacianDonarium',
    'decoratedRomanInitials',
    'frederickat',
    'goudy',
    'homespun',
    'medusa',
    'miniver',
    'mountains',
    'praetoria',
    'princessSofia',
  ]

  ngAfterViewInit(): void {
    this.rerender();
  }

  getRandomFontName(): string {
    return this.fonts[Math.floor(Math.random() * this.fonts.length)];
  }

  getFont() {
    return 'font-family: ' + this.getRandomFontName();
  }

  rerender() {
    setInterval(() => {
      this.title = 'Igor Nascimento';
    }, 1200);
  }
}

<div class="title" #container>

    <p *ngFor="let letter of splitedTitle" [style]="getFont()">{{ letter }}</p>

</div>

// src/components/Banner/index.tsx
import { useEffect, useState } from "react";
import { BannerContainer, BannerImage, ContainerHolder, TitleName } from "./styles";

const fonts = [
    'butterfly',
    'caesarDressing',
    'cairoVariable',
    'chelseaMarket',
    'comingSoon',
    'constantine',
    'craftyGirls',
    'dacianDonarium',
    'decoratedRomanInitials',
    'frederickat',
    'goudy',
    'homespun',
    'medusa',
    'miniver',
    'mountains',
    'praetoria',
    'princessSofia',
]

export default function Banner() {

    const [currentFont, setCurrentFont] = useState(fonts[0]);

    useEffect(() => {
        const interval = setInterval(() => {
            let font;
            do {
                font = fonts[Math.floor(Math.random() * fonts.length)];
            } while (currentFont == font);
            setCurrentFont(font);
        }, 700);
        return () => clearInterval(interval);
    }, []);

    return (
        <BannerContainer>
            <BannerImage></BannerImage>
            <ContainerHolder></ContainerHolder>
            <TitleName font={currentFont}>Igor Nascimento</TitleName>
        </BannerContainer>
    )
}
